"""
Mappings to help 'clean' data (merge duplicate team names, etc)
"""

TEAM_ABBREVIATION_MAP = {
    "AF":   {"abbrev": "AF",   "name": "Air Force"},
    "AFA":  {"abbrev": "AF",   "name": "Air Force"},
    "ALA":  {"abbrev": "ALA",  "name": "Alabama"},
    "APP":  {"abbrev": "APP",  "name": "Appalachian State"},
    "ARIZ": {"abbrev": "ARIZ", "name": "Arizona"},
    "ARK":  {"abbrev": "ARK",  "name": "Arkansas"},
    "ARMY": {"abbrev": "ARMY", "name": "Army"},
    "ASU":  {"abbrev": "ASU",  "name": "Arizona State"},
    "AUB":  {"abbrev": "AUB",  "name": "Auburn"},
    "BALL": {"abbrev": "BALL", "name": "Ball State"},
    "BAY":  {"abbrev": "BAY",  "name": "Baylor"},
    "BC":   {"abbrev": "BC",   "name": "Boston College"},
    "BGSU": {"abbrev": "BGSU",   "name": "Bowling Green"},
    "BOIS": {"abbrev": "BOIS", "name": "Boise State"},
    "BSU":  {"abbrev": "BSU",  "name": "Boise State"},
    "BUFF": {"abbrev": "BUFF", "name": "Buffalo"},
    "BYU":  {"abbrev": "BYU",  "name": "BYU"},
    "CAL":  {"abbrev": "CAL",  "name": "California"},
    "CCU":  {"abbrev": "CCU",  "name": "Coastal Carolina"},
    "CIN":  {"abbrev": "CIN",  "name": "Cincinnati"},
    "CLEM": {"abbrev": "CLEM", "name": "Clemson"},
    "CMU":  {"abbrev": "CMU",  "name": "Central Michigan"},
    "COLO": {"abbrev": "COLO", "name": "Colorado"},
    "CONN": {"abbrev": "CONN", "name": "Connecticut"},
    "CSU":  {"abbrev": "CSU",  "name": "Colorado State"},
    "DUKE": {"abbrev": "DUKE", "name": "Duke"},
    "ECU":  {"abbrev": "ECU",  "name": "East Carolina"},
    "FLA":  {"abbrev": "FLA",  "name": "Florida"},
    "FRES": {"abbrev": "FRES", "name": "Fresno State"},
    "FSU":  {"abbrev": "FSU",  "name": "Florida State"},
    "GT":   {"abbrev": "GT",   "name": "Georgia Tech"},
    "HAW":  {"abbrev": "HAW",  "name": "Hawai'i"},
    "HOU":  {"abbrev": "HOU",  "name": "Houston"},
    "ILL":  {"abbrev": "ILL",  "name": "Illinois"},
    "IND":  {"abbrev": "IND",  "name": "Indiana"},
    "IOWA": {"abbrev": "IOWA", "name": "Iowa"},
    "ISU":  {"abbrev": "ISU",  "name": "Iowa State"},
    "IU":   {"abbrev": "IU",   "name": "Indiana"},
    "JMU":  {"abbrev": "JMU",  "name": "James Madison"},
    "KENT": {"abbrev": "KENT", "name": "Kent State"},
    "KSU":  {"abbrev": "KSU",  "name": "Kansas State"},
    "KU":   {"abbrev": "KU",   "name": "Kansas"},
    "LIB":  {"abbrev": "LIB",  "name": "Liberty"},
    "LOU":  {"abbrev": "LOU",  "name": "Louisville"},
    "LSU":  {"abbrev": "LSU",  "name": "LSU"},
    "LT":   {"abbrev": "LT",   "name": "Louisiana Tech"},
    "MD":   {"abbrev": "MD",   "name": "Maryland"},
    "MEM":  {"abbrev": "MEM",  "name": "Memphis"},
    "MIA":  {"abbrev": "MIAOH",  "name": "Miami (OH)"},
    "M-OH":  {"abbrev": "MIAOH",  "name": "Miami (OH)"},
    "MIAMI": {"abbrev": "MIAMI","name": "Miami (FL)"},
    "MICH": {"abbrev": "MICH", "name": "Michigan"},
    "MINN": {"abbrev": "MINN", "name": "Minnesota"},
    "MISS": {"abbrev": "MISS", "name": "Ole Miss"},
    "MIZ":  {"abbrev": "MIZ",  "name": "Missouri"},
    "MRSH": {"abbrev": "MRSH", "name": "Marshall"},
    "MSST": {"abbrev": "MSST", "name": "Mississippi State"},
    "MSU":  {"abbrev": "MSU",  "name": "Michigan State"},
    "NAVY": {"abbrev": "NAVY", "name": "Navy"},
    "NCST": {"abbrev": "NCST", "name": "NC State"},
    "NCSU": {"abbrev": "NCSU", "name": "NC State"},
    "ND":   {"abbrev": "ND",   "name": "Notre Dame"},
    "NEB":  {"abbrev": "NEB",  "name": "Nebraska"},
    "NEV":  {"abbrev": "NEV",  "name": "Nevada"},
    "NIU":  {"abbrev": "NIU",  "name": "Northern Illinois"},
    "NU":   {"abbrev": "NW",   "name": "Northwestern"},
    "NW":   {"abbrev": "NW",   "name": "Northwestern"},
    "OHIO": {"abbrev": "OHIO", "name": "Ohio"},
    "OKLA": {"abbrev": "OKLA", "name": "Oklahoma"},
    "OKST": {"abbrev": "OKST", "name": "Oklahoma State"},
    "ORE":  {"abbrev": "ORE",  "name": "Oregon"},
    "ORST": {"abbrev": "ORST", "name": "Oregon State"},
    "OSU":  {"abbrev": "OSU",  "name": "Ohio State"},
    "OU":   {"abbrev": "OU",   "name": "Oklahoma"},
    "PITT": {"abbrev": "PITT", "name": "Pittsburgh"},
    "PSU":  {"abbrev": "PSU",  "name": "Penn State"},
    "PUR":  {"abbrev": "PUR",  "name": "Purdue"},
    "RUTG": {"abbrev": "RUTG", "name": "Rutgers"},
    "SC":   {"abbrev": "SC",   "name": "South Carolina"},
    "SDSU": {"abbrev": "SDSU", "name": "San Diego State"},
    "SJSU": {"abbrev": "SJSU", "name": "San José State"},
    "SMU":  {"abbrev": "SMU",  "name": "SMU"},
    "STAN": {"abbrev": "STAN", "name": "Stanford"},
    "SYR":  {"abbrev": "SYR",  "name": "Syracuse"},
    "TA&M": {"abbrev": "TA&M", "name": "Texas A&M"},
    "TCU":  {"abbrev": "TCU",  "name": "TCU"},
    "TEM":  {"abbrev": "TEM",  "name": "Temple"},
    "TENN": {"abbrev": "TENN", "name": "Tennessee"},
    "TEX":  {"abbrev": "TEX",  "name": "Texas"},
    "TLSA": {"abbrev": "TLSA", "name": "Tulsa"},
    "TOL":  {"abbrev": "TOL",  "name": "Toledo"},
    "TROY": {"abbrev": "TROY", "name": "Troy"},
    "TTU":  {"abbrev": "TTU",  "name": "Texas Tech"},
    "TULN": {"abbrev": "TULN", "name": "Tulane"},
    "UAB":  {"abbrev": "UAB",  "name": "UAB"},
    "UCF":  {"abbrev": "UCF",  "name": "UCF"},
    "UCLA": {"abbrev": "UCLA", "name": "UCLA"},
    "UGA":  {"abbrev": "UGA",  "name": "Georgia"},
    "UK":   {"abbrev": "UK",   "name": "Kentucky"},
    "UL":   {"abbrev": "UL",   "name": "Louisiana"},
    "UNC":  {"abbrev": "UNC",  "name": "North Carolina"},
    "UNLV": {"abbrev": "UNLV", "name": "UNLV"},
    "USC":  {"abbrev": "USC",  "name": "USC"},
    "USF":  {"abbrev": "USF",  "name": "South Florida"},
    "USM":  {"abbrev": "USM",  "name": "Southern Miss"},
    "USU":  {"abbrev": "USU",  "name": "Utah State"},
    "UTAH": {"abbrev": "UTAH", "name": "Utah"},
    "UTEP": {"abbrev": "UTEP", "name": "UTEP"},
    "UTSA": {"abbrev": "UTSA", "name": "UTSA"},
    "UVA":  {"abbrev": "UVA",  "name": "Virginia"},
    "VAN":  {"abbrev": "VAN",  "name": "Vanderbilt"},
    "VT":   {"abbrev": "VT",   "name": "Virginia Tech"},
    "WAKE": {"abbrev": "WAKE", "name": "Wake Forest"},
    "WASH": {"abbrev": "WASH", "name": "Washington"},
    "WIS":  {"abbrev": "WIS",  "name": "Wisconsin"},
    "WISC": {"abbrev": "WIS",  "name": "Wisconsin"},
    "WKU":  {"abbrev": "WKU",  "name": "W Kentucky"},
    "WMU":  {"abbrev": "WMU",  "name": "W Michigan"},
    "WSU":  {"abbrev": "WSU",  "name": "Washington St"},
    "WVU":  {"abbrev": "WVU",  "name": "West Virginia"},
}
